# Generated by Django 3.0.2 on 2020-07-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coder', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='code',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='code',
            old_name='title',
            new_name='roll_no',
        ),
        migrations.RemoveField(
            model_name='code',
            name='author',
        ),
    ]
